import { Canvas, useFrame, useLoader, useThree } from '@react-three/fiber'
import { ContactShadows, Edges, Html, OrbitControls, OrthographicCamera } from '@react-three/drei'
import { Suspense, useEffect, useMemo, useRef, useState } from 'react'
import type { Mesh, Object3D } from 'three'
import * as THREE from 'three'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js'
import '../../App.css'

type Vec3 = [number, number, number]
const STORY_DURATION = 40
const ACTIVE_BLUE = '#9ed8ff'
const MAIN_BLUE = '#3f73ff'
const WHITE_EDGE = '#eef1f6'
const SOFT_EDGE = '#77818f'
const MUTED_EDGE = '#46515e'
const BROOCH = new THREE.Vector3(0.02, 1.24, 0.36)
function clamp01(value: number) { return Math.min(1, Math.max(0, value)) }
function smoothStep(value: number, start: number, end: number) { const x = clamp01((value - start) / (end - start)); return x * x * (3 - 2 * x) }
function visibilityBetween(time: number, start: number, end: number, fade = 0.55) { return smoothStep(time, start, start + fade) * (1 - smoothStep(time, end, end + fade)) }
function pulse(time: number, speed = 1) { return 0.5 + Math.sin(time * speed) * 0.5 }
function wrapTime(time: number) { return time % STORY_DURATION }
function useStoryClock() { const [time, setTime] = useState(0); useEffect(() => { const startedAt = performance.now(); let frame = 0; const tick = () => { setTime(wrapTime((performance.now() - startedAt) / 1000)); frame = requestAnimationFrame(tick) }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame) }, []); return time }
function getPathPoint(points: THREE.Vector3[], progress: number) { const lengths = points.slice(0, -1).map((p, i) => p.distanceTo(points[i + 1])); const total = lengths.reduce((s, l) => s + l, 0); let target = clamp01(progress) * total; for (let i = 0; i < lengths.length; i += 1) { const l = lengths[i]; if (target <= l) return points[i].clone().lerp(points[i + 1], l <= 0.001 ? 0 : target / l); target -= l } return points[points.length - 1].clone() }
function CameraMotion({ time }: { time: number }) { const { camera } = useThree(); const lookAt = useRef(new THREE.Vector3(0, 1.25, 0.05)); const frames = useMemo(() => [{ at: 0, position: new THREE.Vector3(2.6, 2.1, 3.15), look: new THREE.Vector3(0, 1.2, 0.12), zoom: 126 }, { at: 6, position: new THREE.Vector3(1.85, 1.72, 2.25), look: new THREE.Vector3(0.04, 1.22, 0.36), zoom: 158 }, { at: 13, position: new THREE.Vector3(2.6, 2.35, 3.05), look: new THREE.Vector3(0.02, 1.66, 0.05), zoom: 122 }, { at: 24, position: new THREE.Vector3(2.35, 2.08, 2.72), look: new THREE.Vector3(0.32, 1.38, 0.28), zoom: 134 }, { at: 36, position: new THREE.Vector3(2.15, 1.82, 2.58), look: new THREE.Vector3(0.06, 1.1, 0.35), zoom: 146 }, { at: 39.8, position: new THREE.Vector3(2.15, 1.82, 2.58), look: new THREE.Vector3(0.06, 1.1, 0.35), zoom: 146 }], []); useFrame((_, delta) => { const index = Math.max(0, frames.findIndex((f, i) => { const n = frames[i + 1]; return n ? time >= f.at && time < n.at : time >= f.at })); const current = frames[index], next = frames[Math.min(index + 1, frames.length - 1)]; const blend = current === next ? 0 : smoothStep(time, current.at, next.at); const targetPosition = current.position.clone().lerp(next.position, blend); const targetLookAt = current.look.clone().lerp(next.look, blend); const targetZoom = current.zoom + (next.zoom - current.zoom) * blend; const ease = 1 - Math.exp(-delta * 2.7); camera.position.lerp(targetPosition, ease); lookAt.current.lerp(targetLookAt, ease); camera.zoom += (targetZoom - camera.zoom) * ease; camera.lookAt(lookAt.current); camera.updateProjectionMatrix() }); return null }
function LineBox({ position, scale, rotation = [0, 0, 0], color = '#101721', edge = WHITE_EDGE, opacity = 0.72, emissive = '#000', emissiveIntensity = 0 }: { position: Vec3; scale: Vec3; rotation?: Vec3; color?: string; edge?: string; opacity?: number; emissive?: string; emissiveIntensity?: number }) { return <mesh position={position} rotation={rotation} scale={scale} castShadow receiveShadow><boxGeometry /><meshStandardMaterial color={color} emissive={emissive} emissiveIntensity={emissiveIntensity} roughness={0.78} transparent opacity={opacity} /><Edges color={edge} threshold={10} /></mesh> }
function styleImported(root: Object3D, tint = '#101721', edge = WHITE_EDGE, fillOpacity = 0.46, lineOpacity = 0.32, threshold = 42) { root.traverse((child) => { const mesh = child as Mesh; if (!mesh.isMesh || !mesh.geometry) return; mesh.castShadow = true; mesh.receiveShadow = true; mesh.material = new THREE.MeshStandardMaterial({ color: tint, emissive: tint, emissiveIntensity: 0.01, roughness: 0.82, transparent: true, opacity: fillOpacity }); mesh.add(new THREE.LineSegments(new THREE.EdgesGeometry(mesh.geometry, threshold), new THREE.LineBasicMaterial({ color: edge, transparent: true, opacity: lineOpacity }))) }) }
function fitObject(root: Object3D, size = 1) { const box = new THREE.Box3().setFromObject(root); const d = new THREE.Vector3(); box.getSize(d); root.scale.multiplyScalar(size / Math.max(d.x, d.y, d.z, 0.001)); const fitted = new THREE.Box3().setFromObject(root); const c = new THREE.Vector3(); fitted.getCenter(c); root.position.sub(c); root.position.y -= fitted.min.y - c.y }
function Model({ src, position, rotation = [0, 0, 0], scale = 1, edge = WHITE_EDGE, opacity = 0.46, lineOpacity = 0.32 }: { src: string; position: Vec3; rotation?: Vec3; scale?: number; edge?: string; opacity?: number; lineOpacity?: number }) { const gltf = useLoader(GLTFLoader, src); const object = useMemo(() => { const clone = gltf.scene.clone(true); fitObject(clone, scale); styleImported(clone, '#101721', edge, opacity, lineOpacity); return clone }, [edge, gltf.scene, lineOpacity, opacity, scale]); return <primitive object={object} position={position} rotation={rotation} /> }

function SegmentTube({ start, end, width, opacity, color }: { start: THREE.Vector3; end: THREE.Vector3; width: number; opacity: number; color: string }) { const geometry = useMemo(() => new THREE.TubeGeometry(new THREE.LineCurve3(start, end), 18, width, 6, false), [end, start, width]); return <mesh geometry={geometry}><meshBasicMaterial color={color} transparent opacity={opacity} /></mesh> }
function AnimatedRoute({ points, time, start, end, holdUntil, color = ACTIVE_BLUE, width = 0.006, opacity = 0.62 }: { points: THREE.Vector3[]; time: number; start: number; end: number; holdUntil: number; color?: string; width?: number; opacity?: number }) { const progress = clamp01((time - start) / (end - start)); const visibility = smoothStep(time, start, start + 0.35) * (1 - smoothStep(time, holdUntil, holdUntil + 0.65)); const lengths = useMemo(() => { let total = 0; const segments = points.slice(0, -1).map((p, i) => { const l = p.distanceTo(points[i + 1]); total += l; return l }); return { segments, total } }, [points]); const movingPoint = getPathPoint(points, progress); if (visibility <= 0.01 || progress <= 0.01 || lengths.total <= 0.001) return null; let drawn = progress * lengths.total; return <group>{points.slice(0, -1).map((p, i) => { const l = lengths.segments[i]; const amount = clamp01(drawn / l); drawn -= l; if (amount <= 0) return null; return <SegmentTube key={i} start={p} end={p.clone().lerp(points[i + 1], amount)} width={width} opacity={0.08 + visibility * opacity} color={color} /> })}<mesh position={[movingPoint.x, movingPoint.y, movingPoint.z]}><sphereGeometry args={[width * 3.8, 14, 10]} /><meshBasicMaterial color={color} transparent opacity={0.58 + pulse(time, 8.5) * 0.32} /></mesh></group> }
function EvansBrooch({ time }: { time: number }) { return <group position={[BROOCH.x, BROOCH.y, BROOCH.z]} rotation={[Math.PI / 2, 0, 0]}><mesh><torusGeometry args={[0.05, 0.004, 10, 36]} /><meshBasicMaterial color={ACTIVE_BLUE} transparent opacity={0.76} /></mesh><mesh position={[0, 0, 0.006]}><sphereGeometry args={[0.027, 18, 12]} /><meshStandardMaterial color="#101722" emissive={ACTIVE_BLUE} emissiveIntensity={0.42 + pulse(time, 2.4) * 0.26} roughness={0.55} /></mesh></group> }
function StandingPerson({ time, position = [0,0,0] as Vec3, opacity = 1 }: { time: number; position?: Vec3; opacity?: number }) { return <group position={position}><Model src="/models/base-male.glb" position={[0,0,0]} rotation={[0,-0.1,0]} scale={1.5} opacity={0.34 * opacity} lineOpacity={0.3 * opacity}/><LineBox position={[0.26, 0.78, 0.32]} scale={[0.11, 0.18, 0.018]} rotation={[0.15, 0.08, -0.14]} color="#06111f" edge={ACTIVE_BLUE} opacity={0.42 * opacity} emissive={ACTIVE_BLUE} emissiveIntensity={0.08} />{opacity >= 1 && <EvansBrooch time={time} />}</group> }
function SubwayCar() { return <group><mesh rotation={[-Math.PI / 2,0,0]} position={[0,0,-0.25]} receiveShadow><planeGeometry args={[7.4,4.6]} /><meshStandardMaterial color="#05080d" roughness={0.86} /><Edges color={MUTED_EDGE} threshold={5} /></mesh><Model src="/models/poly-pizza/locomotive-passenger-carriage.glb" position={[0,0.72,-1.12]} rotation={[0,Math.PI/2,0]} scale={3.45} opacity={0.36} lineOpacity={0.3} edge={SOFT_EDGE}/><Model src="/models/poly-pizza/high-speed-wagon.glb" position={[-2.05,0.66,-1.34]} rotation={[0,Math.PI/2,0]} scale={2.45} opacity={0.22} lineOpacity={0.22} edge={MUTED_EDGE}/><LineBox position={[0,2.35,-0.35]} scale={[6.8,0.08,3.7]} color="#060910" edge={MUTED_EDGE} opacity={0.16}/><LineBox position={[0,2.08,0.2]} scale={[6.4,0.035,0.035]} color="#101721" edge={SOFT_EDGE} opacity={0.42}/>{[-2.2,-0.9,0.4,1.7].map(x => <group key={x} position={[x,1.78,0.2]}><mesh position={[0,-0.06,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[0.08,0.006,8,24]} /><meshBasicMaterial color={SOFT_EDGE} transparent opacity={0.42} /></mesh></group>)}<StandingPerson time={0} position={[-1.9,0,-0.45]} opacity={0.38}/><StandingPerson time={0} position={[1.75,0,-0.55]} opacity={0.32}/></group> }
function DialogueLayer({ time }: { time: number }) { const entries = [{start:0.7,end:5.2,kind:'person',title:'李明',body:'Evans，昨晚老王在微信发的那个 banner 改版需求，我今天要安排进度，帮我看看怎么排。',position:[-0.52,1.64,0.76] as Vec3},{start:5.5,end:9.2,kind:'voice',title:'Evans',body:'找到了。老王要的是首页 banner 改版加落地页，周五 18:00 截止。',position:[-0.52,1.76,0.76] as Vec3},{start:15.0,end:17.6,kind:'voice',title:'Evans',body:'我已经做了三件事。',position:[-0.52,1.76,0.76] as Vec3},{start:24.0,end:29.5,kind:'voice',title:'Evans',body:'你只需要看一下小蕾的 brief 草稿，点确认。其他全自动了。',position:[-0.52,1.76,0.76] as Vec3}]; return <>{entries.map(e => { const opacity=visibilityBetween(time,e.start,e.end); if(opacity<=0.01) return null; return <Html key={e.start} position={e.position} center distanceFactor={7.8} transform sprite occlude={false} zIndexRange={[38,0]}><div className={`object-label object-label--${e.kind} transit-dialog`} style={{opacity, transform:`translateY(${8-opacity*8}px) scale(${0.94+opacity*0.06})`}}><strong>{e.title}</strong><span>{e.body}</span></div></Html>})}</> }
function ScanCard({ time }: { time: number }) { const opacity=visibilityBetween(time,6.2,13.6); if(opacity<=0.01) return null; return <Html position={[0,2.05,0.08]} center distanceFactor={8.2} transform sprite occlude={false} zIndexRange={[36,0]}><div className="transit-scan-card" style={{opacity}}><strong>微信原文 + 团队画像</strong><span>老王：banner + 落地页 / DDL 周五 / 上线周一</span><span>小蕾设计 1.5 天 · 小冯前端周四后可投入</span></div></Html> }
function GanttCard({ time }: { time: number }) { const opacity=visibilityBetween(time,11.8,38); if(opacity<=0.01) return null; return <Html position={[0.28,1.72,0.42]} center distanceFactor={8.8} transform sprite occlude={false} zIndexRange={[42,0]}><div className="transit-gantt-card" style={{opacity, transform:`translateY(${5-opacity*5}px) scale(${0.68+opacity*0.07})`}}><div className="transit-topbar"><span>banner 改版-0518</span><i>自动排期</i></div><header><small>缓冲 0.5 天 · 风险低</small><strong>项目排期甘特图</strong></header><div className="gantt-row"><b>小蕾</b><span><i style={{width:'42%'}} /></span><em>周二-周三</em></div><div className="gantt-row"><b>小冯</b><span><i style={{marginLeft:'42%',width:'32%'}} /></span><em>周四-周五</em></div><div className="gantt-row"><b>李明</b><span><i style={{marginLeft:'72%',width:'13%'}} /></span><em>周五下午</em></div><div className="gantt-row"><b>上线</b><span><i style={{marginLeft:'88%',width:'7%'}} /></span><em>下周一</em></div></div></Html> }
function BranchCards({ time }: { time: number }) { const opacity=visibilityBetween(time,17.2,38); const sent=smoothStep(time,29,31); if(opacity<=0.01) return null; const cards: Array<[string,string,Vec3]>=[['飞书项目页','banner 改版-0518｜李明/小蕾/小冯｜已创建',[-1.35,1.14,0.7]],['需求 brief 草稿','TO 小蕾｜老王原文整理 5 点｜草稿待确认',[1.62,1.26,0.68]],['日历评审邀请','周五 14:00-16:00｜三人邀请｜待回复',[1.42,1.78,0.38]]]; return <>{cards.map(([title,body,pos]) => <Html key={title} position={pos} center distanceFactor={8.5} transform sprite occlude={false} zIndexRange={[39,0]}><div className="transit-branch-card" style={{opacity, transform:`translateY(${5-opacity*5}px) scale(${0.78+opacity*0.06})`}}><strong>{title}</strong><span>{body}</span>{sent>0.01 && <em style={{opacity:sent}}>已发出</em>}</div></Html>)}</> }
function DispatchMotion({ time }: { time: number }) { const scan=useMemo(()=>new THREE.Vector3(0,1.95,0.1),[]); const gantt=useMemo(()=>new THREE.Vector3(0.28,1.65,0.42),[]); const branches=useMemo(()=>[new THREE.Vector3(-1.35,1.14,0.7),new THREE.Vector3(1.62,1.26,0.68),new THREE.Vector3(1.42,1.78,0.38)],[]); return <group><AnimatedRoute points={[BROOCH,new THREE.Vector3(-0.24,1.56,0.28),scan]} time={time} start={5.8} end={7.2} holdUntil={13.4} color={ACTIVE_BLUE} width={0.0048} opacity={0.48}/><AnimatedRoute points={[scan,new THREE.Vector3(0.02,1.88,0.22),gantt]} time={time} start={10.6} end={12.2} holdUntil={17.0} color={MAIN_BLUE} width={0.006} opacity={0.62}/>{branches.map((b,i)=><AnimatedRoute key={i} points={[gantt,new THREE.Vector3((b.x+gantt.x)/2,1.56+i*0.08,0.5),b]} time={time} start={16.2+i*0.25} end={18.0+i*0.25} holdUntil={31.5} color={MAIN_BLUE} width={0.0055} opacity={0.58}/>) }{branches.map((b,i)=><AnimatedRoute key={`send-${i}`} points={[b,new THREE.Vector3(b.x*1.22,b.y+0.2,b.z+0.15)]} time={time} start={29+i*0.12} end={30.4+i*0.12} holdUntil={33} color={MAIN_BLUE} width={0.005} opacity={0.55}/>) }<ScanCard time={time}/><GanttCard time={time}/><BranchCards time={time}/><DialogueLayer time={time}/></group> }
function TransitSet({ time }: { time: number }) { return <group><SubwayCar/><StandingPerson time={time} position={[0,0,0.18]}/><DispatchMotion time={time}/></group> }
function AnimatedScene({ time }: { time: number }) { return <><color attach="background" args={['#05080d']} /><fog attach="fog" args={['#05080d',5.6,11.5]} /><OrthographicCamera makeDefault position={[2.6,2.1,3.15]} zoom={122}/><CameraMotion time={time}/><ambientLight intensity={0.42}/><hemisphereLight intensity={0.26} color="#d8e6ff" groundColor="#080604"/><directionalLight castShadow intensity={1.05} position={[4.2,6.8,4.6]} shadow-mapSize-width={2048} shadow-mapSize-height={2048}/><spotLight castShadow intensity={6.2} angle={0.46} penumbra={0.84} position={[0.4,3.6,2.0]} color="#dcecff"/><pointLight intensity={0.9} distance={2.2} position={[BROOCH.x,BROOCH.y,BROOCH.z]} color={ACTIVE_BLUE}/><group rotation={[0,-0.06,0]}><TransitSet time={time}/></group><ContactShadows position={[0,0.02,0]} opacity={0.58} scale={9} blur={2.35} far={6} color="#000000"/><OrbitControls enabled={false} enablePan={false} enableZoom={false} enableRotate={false} target={[0,1.18,0.15]}/></> }
function SceneOverlay({ time }: { time: number }) { return <div className="story-progress"><i style={{ width: `${(time / STORY_DURATION) * 100}%` }} /></div> }
export function TransitHandoffExperience() { const time=useStoryClock(); return <section className="interior-shell" aria-label="地铁车厢跨工具任务交接三维静态场景"><Canvas shadows dpr={[1,2]}><Suspense fallback={null}><AnimatedScene time={time}/></Suspense></Canvas><SceneOverlay time={time}/></section> }
export default TransitHandoffExperience
